"""Added metric model

Revision ID: b43a85ed5ebf
Revises: 23cbc3d03086
Create Date: 2021-04-23 15:20:32.384544

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b43a85ed5ebf'
down_revision = '23cbc3d03086'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('evaluation_metric',
    sa.Column('shape_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('value', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['shape_id'], ['api_shape.id'], ),
    sa.PrimaryKeyConstraint('shape_id', 'name')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('evaluation_metric')
    # ### end Alembic commands ###
